config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :nature_of_reviews
  end
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	#resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	#resources :advertises
  	resources :suppliers
  	#resources :resource_types
    resources :seos
    #resources :company_performances
    #resources :abuse_reports
    
    
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/nature_of_reviews_controller.rb
class Admin::NatureOfReviewsController < ApplicationController
  before_action :set_admin_nature_of_review, only: [:show, :edit, :update, :destroy]

  # GET /admin/nature_of_reviews
  # GET /admin/nature_of_reviews.json
  def index
    @admin_nature_of_reviews = Admin::NatureOfReview.all
  end

  # GET /admin/nature_of_reviews/1
  # GET /admin/nature_of_reviews/1.json
  def show
  end

  # GET /admin/nature_of_reviews/new
  def new
    @admin_nature_of_review = Admin::NatureOfReview.new
  end

  # GET /admin/nature_of_reviews/1/edit
  def edit
  end

  # POST /admin/nature_of_reviews
  # POST /admin/nature_of_reviews.json
  def create
    @admin_nature_of_review = Admin::NatureOfReview.new(admin_nature_of_review_params)

    respond_to do |format|
      if @admin_nature_of_review.save
        format.html { redirect_to @admin_nature_of_review, notice: 'Nature of review was successfully created.' }
        format.json { render :show, status: :created, location: @admin_nature_of_review }
      else
        format.html { render :new }
        format.json { render json: @admin_nature_of_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/nature_of_reviews/1
  # PATCH/PUT /admin/nature_of_reviews/1.json
  def update
    respond_to do |format|
      if @admin_nature_of_review.update(admin_nature_of_review_params)
        format.html { redirect_to @admin_nature_of_review, notice: 'Nature of review was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_nature_of_review }
      else
        format.html { render :edit }
        format.json { render json: @admin_nature_of_review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/nature_of_reviews/1
  # DELETE /admin/nature_of_reviews/1.json
  def destroy
    @admin_nature_of_review.destroy
    respond_to do |format|
      format.html { redirect_to admin_nature_of_reviews_url, notice: 'Nature of review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_nature_of_review
      @admin_nature_of_review = Admin::NatureOfReview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_nature_of_review_params
      params.require(:admin_nature_of_review).permit(:title, :user_id, :review_type)
    end
end

app/helpers/admin/nature_of_reviews_helper.rb
module Admin::NatureOfReviewsHelper
end

app/views/admin/nature_of_reviews/_form.html.erb
<%= form_for(admin_nature_of_review) do |f| %>
  <% if admin_nature_of_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_nature_of_review.errors.count, "error") %> prohibited this admin_nature_of_review from being saved:</h2>

      <ul>
      <% admin_nature_of_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :review_type %>
    <%= f.text_field :review_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/nature_of_reviews/edit.html.erb
<h1>Editing Admin Nature Of Review</h1>

<%= render 'form', admin_nature_of_review: @admin_nature_of_review %>

<%= link_to 'Show', @admin_nature_of_review %> |
<%= link_to 'Back', admin_nature_of_reviews_path %>

app/views/admin/nature_of_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Nature Of Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Review type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_nature_of_reviews.each do |admin_nature_of_review| %>
      <tr>
        <td><%= admin_nature_of_review.title %></td>
        <td><%= admin_nature_of_review.user_id %></td>
        <td><%= admin_nature_of_review.review_type %></td>
        <td><%= link_to 'Show', admin_nature_of_review %></td>
        <td><%= link_to 'Edit', edit_admin_nature_of_review_path(admin_nature_of_review) %></td>
        <td><%= link_to 'Destroy', admin_nature_of_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Nature Of Review', new_admin_nature_of_review_path %>

app/views/admin/nature_of_reviews/new.html.erb
<h1>New Admin Nature Of Review</h1>

<%= render 'form', admin_nature_of_review: @admin_nature_of_review %>

<%= link_to 'Back', admin_nature_of_reviews_path %>

app/views/admin/nature_of_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @admin_nature_of_review.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @admin_nature_of_review.user_id %>
</p>

<p>
  <strong>Review type:</strong>
  <%= @admin_nature_of_review.review_type %>
</p>

<%= link_to 'Edit', edit_admin_nature_of_review_path(@admin_nature_of_review) %> |
<%= link_to 'Back', admin_nature_of_reviews_path %>