config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :nature_of_reviews
  end
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	#resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	#resources :advertises
  	resources :suppliers
  	#resources :resource_types
    resources :seos
    #resources :company_performances
    #resources :abuse_reports
    
    
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :title, presence: true, uniqueness: true
	belongs_to :industry
	has_many :addresses
	has_many :towns, through: :addresses
	has_many :reviews

  # scope :registered, -> { where(is_registered: true) }
  # scope :un_registered, -> { where(is_registered: false) }

  scope :within_range , -> (start_date, end_date) { where("created_at >= ? AND created_at <= ?", start_date, end_date) unless start_date.blank? and end_date.blank? }
  scope :by_industry, -> (industry_id) { where("industry_id = ?", industry_id)  unless industry_id.blank? }
  scope :by_town, -> (town_id) { where("town_id = ?", town_id) unless town_id.blank? }
  scope :by_company, -> (company_id) { where("id = ?", company_id) unless company_id.blank? }


  def self.search(search)
    search_condition = "%" + search + "%"
    find(:all, :conditions => ['title LIKE ?', search_condition])
  end

  def is_registered?
  	is_registered
  end

  def is_not_registered?
  	!is_registered
  end

end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < AdminController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :get_industries
	before_action :default_tab
  before_action :new_company, :only => [:create]

  #load_and_authorize_resource

  def new_company
    @company = Company.new(company_params)
  end


  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.includes(:industry)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    respond_to do |format|
      if @company.save
        format.html { redirect_to [:admin, @company], notice: 'Company was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to  [:admin, @company], notice: 'Company was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:title, :user_id, :industry_id, :is_registered)
    end

    def get_industries
      @industries = Industry.all
    end

		def default_tab
    	@active_tab = 'companies'
    end
end

app/controllers/companies_controller.rb
# class CompaniesController < ApplicationController
#   before_action :set_company, only: [:show, :edit, :update, :destroy]

#   # GET /companies
#   # GET /companies.json
#   def index
#     @companies = Company.all
#   end

#   # GET /companies/1
#   # GET /companies/1.json
#   def show
#   end

#   # GET /companies/new
#   def new
#     @company = Company.new
#   end

#   # GET /companies/1/edit
#   def edit
#   end

#   # POST /companies
#   # POST /companies.json
#   def create
#     @company = Company.new(company_params)

#     respond_to do |format|
#       if @company.save
#         format.html { redirect_to @company, notice: 'Company was successfully created.' }
#         format.json { render :show, status: :created, location: @company }
#       else
#         format.html { render :new }
#         format.json { render json: @company.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /companies/1
#   # PATCH/PUT /companies/1.json
#   def update
#     respond_to do |format|
#       if @company.update(company_params)
#         format.html { redirect_to @company, notice: 'Company was successfully updated.' }
#         format.json { render :show, status: :ok, location: @company }
#       else
#         format.html { render :edit }
#         format.json { render json: @company.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /companies/1
#   # DELETE /companies/1.json
#   def destroy
#     @company.destroy
#     respond_to do |format|
#       format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_company
#       @company = Company.find(params[:id])
#     end

#     # Never trust parameters from the scary internet, only allow the white list through.
#     def company_params
#       params.require(:company).permit(:title, :user_id, :industry_id, :is_registered)
#     end
# end


class CompaniesController < ApplicationController
  before_filter :get_default_for_filter
  before_action :default_action_tab, :only=>[:conversions, :registered, :unregistered, :polls_bloopers]

  def default_action_tab
    @action = "my_account"
  end

  def user_review
    @nav_tab = "reviews"
    @active_tab = "reviews"
    @active_title = "Reviews"
    @reviews ||= Review.published.order("date")
    review = Review.new(review_params)
    @review_filter = review

    if review.review_type
      @reviews = @reviews.by_review_type review.review_type
    end
    
    if review.industry_id && review.industry_id !=0
      @reviews = @reviews.by_industry(review.industry_id)
    end

    if review.company_id && review.company_id !=0
      @reviews = @reviews.by_company(review.company_id)
    end
    
    if review.town_id && review.town_id !=0
      @reviews = @reviews.by_town(review.town_id)
    end
    
    if review.from_date && review.to_date

      @reviews = @reviews.within_range(review.from_date.to_date,review.to_date.to_date)
    end
  end

  def conversions
    @nav_tab = "reviews"
    @active_tab = "conversions"
    review = Review.new(review_params)
    @review_filter = review
    @rcompanies ||= Supplier.all

    if review.industry_id  && review.industry_id !=0
      @rcompanies = @rcompanies.by_industry(review.industry.title)
    end

    if review.company_id  && review.company_id !=0
      @rcompanies = @rcompanies.by_company(review.company.title)
    end
    
#    if review.town_id && review.town_id !=0
#     @rcompanies = @rcompanies.by_town(review.town_id)
#    end
    
    if review.from_date && review.to_date
      @rcompanies = @rcompanies.within_range(review.from_date.to_date,review.to_date.to_date)
    end
      
  end


  def registered
    @nav_tab = "reviews"
    @active_tab = "registered_companies"
    review = Review.new(review_params)
    @review_filter = review
    @rcompanies ||= Supplier.registered

    if review.industry_id  && review.industry_id !=0
      @rcompanies = @rcompanies.by_industry(review.industry.title)
    end
    
    if review.company_id && review.company_id !=0
      @rcompanies = @rcompanies.by_company(review.company.title)
    end
    
#    if review.town_id && review.town_id !=0
#     @rcompanies = @rcompanies.by_town(review.town_id)
#    end
    
    if review.from_date && review.to_date
      @rcompanies = @rcompanies.within_range(review.from_date.to_date,review.to_date.to_date)
    end
  end

  def unregistered
    @nav_tab = "reviews"
    @active_tab = "unregistered_companies"
    review = Review.new(review_params)
    @review_filter = review
    @rcompanies ||= Supplier.un_registered

    if review.industry_id && review.industry_id !=0
      @rcompanies = @rcompanies.by_industry(review.industry.title)
    end
    
    if review.company_id && review.company_id !=0
      @rcompanies = @rcompanies.by_company(review.company.title)
    end
    
#    if review.town_id && review.town_id !=0
#     @rcompanies = @rcompanies.by_town(review.town_id)
#     end
    
    if review.from_date && review.to_date
      @rcompanies = @rcompanies.within_range(review.from_date.to_date,review.to_date.to_date)
    end
  end

  def polls_bloopers
     @nav_tab = "reviews"
    @active_tab = "polls & bloopers"
    @section = 'polls-bloopers'
    @sub_action = 'polls-bloopers'
    @polls = Poll.all
    review = Review.new(review_params)
    if review.from_date && review.to_date
      @polls = Poll.where("Date(created_at) >= ? AND Date(created_at) <= ?",review.from_date.to_date,review.to_date.to_date)
    end
  end
  
  private

  def get_default_for_filter
    @industries = Industry.all.order(:title)
    @companies = []
    @towns = []
    @locations = []
  end

  def review_params
    if params[:review].present?
      params.require(:review).permit(:industry_id, :company_id, :review_type, :location_id, :town_id, :from_date, :to_date)
    end
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_conversions_filter.html.erb
   <%= stylesheet_link_tag    "jquery.ui.datepicker" %>
 <div class="log-head2new">Filter </div>
               <div class="form-box3new">
        <% @review = Review.new %>
		<%= form_for(@review, :url => conversions_path(@review)) do |f|%>	

                <div class="login-field-box1">
                <div class="text-box1">Industry</div>
                  <%= f.collection_select :industry_id, Industry.order(:title),:id,:title, {:include_blank=>"Select Industry"},:rel => "/industry/companies_by_industry","id"=>"review_industry_id", :class=>"drp-select3new pages", :class=>"field2 slt" %>
   
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Company</div>
 			<%= f.collection_select :company_id, @companies, :id, :title,  {:include_blank=>"Select Company"}, :rel => "/company/towns_by_company","id"=>"review_company_id", :class=>"field2 slt"%>
                </div>
              
                <div class="login-field-box1">
                          	<%= f.submit "Search", :class => "fleft btn2"%>
           
                </div>
                
                
                
            	<div class="clear"></div>
            	<% end %>
            </div>


<style type="text/css">
.field2 {
    background: none repeat scroll 0 0 #e6e6e6;
    border: 0 solid #dddcdc;
    box-shadow: 0 4px 2px -1px #dadada;
    color: #696969;
    float: left;
    font-family: corbel;
    font-size: 13px;
    height: 25px;
    margin: 0;
    padding: 2px 5px;
    width: 170px;
}
</style>

app/views/companies/_poll_filter.html.erb
   <%= stylesheet_link_tag    "jquery.ui.datepicker" %>
 <div class="log-head2new">Filter </div>
               <div class="form-box3new">
        <% @review = Review.new %>
		<%= form_for(@review, :url => polls_bloopers_path(@review)) do |f|%>	
              
                <div class="login-field-box1">
                         <div class="text-box1">Date – From</div>
                  <%= f.text_field :from_date, :id => "datepicker1",:format => "dd-mm-yy" ,:class => "newfield field1 rew1" %>
                <div class="text-box1">Date – To</div>
                  <%= f.text_field :to_date, :id => "datepicker2", :class => "newfield field1 rew1" %>
                      <%= f.submit "Search", :class => "fleft btn2"%>
           
                </div>
                
                
                
            	<div class="clear"></div>
            	<% end %>
            </div>


<style type="text/css">
.field2 {
    background: none repeat scroll 0 0 #e6e6e6;
    border: 0 solid #dddcdc;
    box-shadow: 0 4px 2px -1px #dadada;
    color: #696969;
    float: left;
    font-family: corbel;
    font-size: 13px;
    height: 25px;
    margin: 0;
    padding: 2px 5px;
    width: 170px;
}
</style>

app/views/companies/_registered_filter.html.erb
   <%= stylesheet_link_tag    "jquery.ui.datepicker" %>
 <div class="log-head2new">Filter </div>
               <div class="form-box3new">
        <% @review = Review.new %>
		<%= form_for(@review, :url => registered_path(@review)) do |f|%>	

                <div class="login-field-box1">
                <div class="text-box1">Industry</div>
                  <%= f.collection_select :industry_id, Industry.order(:title),:id,:title, {:include_blank=>"Select Industry"},:rel => "/industry/companies_by_industry","id"=>"review_industry_id", :class=>"drp-select3new pages", :class=>"field2 slt" %>
   
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Company</div>
 			<%= f.collection_select :company_id, @companies, :id, :title,  {:include_blank=>"Select Company"}, :rel => "/company/towns_by_company","id"=>"review_company_id", :class=>"field2 slt"%>
                </div>
                 
               <div class="login-field-box1">
           
                	<%= f.submit "Search", :class => "fleft btn2"%>
           
                </div>
                
                
                
            	<div class="clear"></div>
            	<% end %>
            </div>


<style type="text/css">
.field2 {
    background: none repeat scroll 0 0 #e6e6e6;
    border: 0 solid #dddcdc;
    box-shadow: 0 4px 2px -1px #dadada;
    color: #696969;
    float: left;
    font-family: corbel;
    font-size: 13px;
    height: 25px;
    margin: 0;
    padding: 2px 5px;
    width: 170px;
}
</style>

app/views/companies/_review_filter.html.erb
   <%= stylesheet_link_tag    "jquery.ui.datepicker" %>
 <div class="log-head2new">Filter </div>
               <div class="form-box3new">
        <% @review = Review.new %>
		<%= form_for(@review, :url => user_review_path(@review),method: :get) do |f|%>	

                <div class="login-field-box1">
                <div class="text-box1">Industry</div>
                  <%= f.collection_select :industry_id, Industry.order(:title),:id,:title, {:include_blank=>"Select Industry"},:rel => "/industry/companies_by_industry","id"=>"review_industry_id", :class=>"drp-select3new pages", :class=>"field2 slt" %>
   
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Company</div>
 			<%= f.collection_select :company_id, @companies, :id, :title,  {:include_blank=>"Select Company"}, :rel => "/company/towns_by_company","id"=>"review_company_id", :class=>"field2 slt"%>
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Town</div>

                 <%= f.collection_select :town_id, @towns, :id, :title, {:include_blank=>"Select Town"}, :rel => "/town/locations_by_town_and_company","id"=>"review_town_id", :class=>"field2 slt"%>
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Location</div>

               <%= f.collection_select :location_id, @locations ,:id ,:title, {:include_blank=>"Select Location"},:class=>"field2 slt" %>
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Review Type</div>

                 <%= f.select :review_type, [ 'Compliment', 'Complaint'] , {:include_blank=>"Select Type"},:class=>"field2 slt"%>
                </div> <div class="login-field-box1">
                <div class="text-box1">Date – From</div>
                	<%= f.text_field :from_date, :id => "datepicker1",:format => "dd-mm-yy" ,:class => "newfield field1 rew1" %>
                <div class="text-box1">Date – To</div>
                	<%= f.text_field :to_date, :id => "datepicker2", :class => "newfield field1 rew1" %>
                	<%= f.submit "Search", :class => "fleft btn2"%>
           
                </div>
                
                
                
            	<div class="clear"></div>
            	<% end %>
            </div>


<style type="text/css">
.field2 {
    background: none repeat scroll 0 0 #e6e6e6;
    border: 0 solid #dddcdc;
    box-shadow: 0 4px 2px -1px #dadada;
    color: #696969;
    float: left;
    font-family: corbel;
    font-size: 13px;
    height: 25px;
    margin: 0;
    padding: 2px 5px;
    width: 170px;
}
</style>

app/views/companies/_unregistered_filter.html.erb
   <%= stylesheet_link_tag    "jquery.ui.datepicker" %>
 <div class="log-head2new">Filter </div>
               <div class="form-box3new">
        <% @review = Review.new %>
		<%= form_for(@review, :url => unregistered_path(@review)) do |f|%>	

                <div class="login-field-box1">
                <div class="text-box1">Industry</div>
                  <%= f.collection_select :industry_id, Industry.order(:title),:id,:title, {:include_blank=>"Select Industry"},:rel => "/industry/companies_by_industry","id"=>"review_industry_id", :class=>"drp-select3new pages", :class=>"field2 slt" %>
   
                </div>
                 <div class="login-field-box1">
                 <div class="text-box1">Company</div>
 			<%= f.collection_select :company_id, @companies, :id, :title,  {:include_blank=>"Select Company"}, :rel => "/company/towns_by_company","id"=>"review_company_id", :class=>"field2 slt"%>
                </div>
         
               <div class="login-field-box1">
                
                	<%= f.submit "Search", :class => "fleft btn2"%>
           
                </div>
                
                
                
            	<div class="clear"></div>
            	<% end %>
            </div>


<style type="text/css">
.field2 {
    background: none repeat scroll 0 0 #e6e6e6;
    border: 0 solid #dddcdc;
    box-shadow: 0 4px 2px -1px #dadada;
    color: #696969;
    float: left;
    font-family: corbel;
    font-size: 13px;
    height: 25px;
    margin: 0;
    padding: 2px 5px;
    width: 170px;
}
</style>

app/views/companies/conversions.html.erb
<link rel="stylesheet" href="/assets/jquery.mCustomScrollbar.css">

  
  <!-- custom scrollbar plugin -->
  <script src="/assets/jquery.mCustomScrollbar.concat.min.js"></script>
  
  <script>
    (function($){
      $(window).load(function(){
        
        $("a[rel='load-content']").click(function(e){
          e.preventDefault();
          var url=$(this).attr("href");
          $.get(url,function(data){
            $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
            //scroll-to appended content 
            $(".content").mCustomScrollbar("scrollTo","h2:last");
          });
        });
        
        $(".content").delegate("a[href='top']","click",function(e){
          e.preventDefault();
          $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
        });
        
      });
    })(jQuery);
  </script>

<%content_for :left do%>
	<span class="span3">
		 <%=render :partial=> "application/my_account_left"%>
	</span>
<%end%>

  <div class="reviews-box1">
                <div class="overflow12">
              <div class="review-center">
              <div class="home-grid">
      <!--<table cellpadding="0" cellspacing="0" class="grid-head-tbl">
                    <tr> 
                         <td width="20%" align="left">Company</td>
                          <td width="20%" align="center" class="bg-image" valign="top">Compliment</td>
                          <td width="20%" align="right">Complaint</td>
                           <td width="20%" align="right">Conversions</td>

                         
                         <td width="6%"></td>
                    </tr>
      </table>-->
              <table cellpadding="0" cellspacing="0" class="grid-head-tb2 ">
                    <tr> 
                         <td width="16%" align="center">Company</td>
                         <td width="4%" align="center"></td>
                         <td width="21%" align="center" class="bg-imagenew" valign="top">Compliment</td>
                         <td width="21%" align="center" class="bg-image1new" valign="top">Complaint</td>
                         <td width="16%" align="center" class="bg-image2new" valign="top">Conversion</td>
                         <td width="3%"></td>
                    </tr>
      </table>
      <div class="content2 mCustomScrollbar">
                <table cellpadding="0" cellspacing="0" class="grid-tbl1">
                          <%@rcompanies.each do |company|%>
                        <tr>
                            <td width="23%"><%=company.supplier_name rescue nil%></td>
                            <td width="4%">&nbsp;</td>
                            <td width="20%" align="center"><%=review_compliment_count(company) rescue nil%> </td>
                            <td width="5%">&nbsp;</td>
                            <td width="20%" align="center"><%=review_complaint_count(company) rescue nil%></td>
                            <td width="1%">&nbsp;</td>
                             <td width="20%" align="center"><%=change_complaint_count(company) rescue nil%> </td>
                           
                          </td>
                        </tr>
                        <% end %>
              </table>
            </div>
      </div>
            
              </div>
                </div>
                <div class="clear"></div>
                
            </div>



<%content_for :right do%>
	<span class="span3">
		 <%=render :partial=> "conversions_filter"%>
	</span>
<%end%>

app/views/companies/polls_bloopers.html.erb
<link rel="stylesheet" href="/assets/jquery.mCustomScrollbar.css">

  
  <!-- custom scrollbar plugin -->
  <script src="/assets/jquery.mCustomScrollbar.concat.min.js"></script>
  
  <script>
    (function($){
      $(window).load(function(){
        
        $("a[rel='load-content']").click(function(e){
          e.preventDefault();
          var url=$(this).attr("href");
          $.get(url,function(data){
            $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
            //scroll-to appended content 
            $(".content").mCustomScrollbar("scrollTo","h2:last");
          });
        });
        
        $(".content").delegate("a[href='top']","click",function(e){
          e.preventDefault();
          $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
        });
        
      });
    })(jQuery);
  </script>
<%content_for :left do%>
	<span class="span3">
		 <%=render :partial=> "application/my_account_left"%>
	</span>
<%end%>

<div class="reviews-box1">
            	
            	<div class="review-center newsize">
            	<div class="home-grid">
			<table cellpadding="0" cellspacing="0" class="grid-head-tb2 newsize ">
                    <tr> 
                         <td width="20%" align="left">Polls & Bloopers</td>
                         </tr>
			</table>
			<div class="content2 newsize mCustomScrollbar">
                  <%@polls.each do |poll|%>
                    <a href="<%= poll_path(poll) %>"> <div class="box1"><p><%= poll.title.truncate(56) rescue nil%></p></div></a>
					
						<%end%>
					
                               
                  
            </div>
			</div>
            
            	</div>
               
                <div class="clear"></div>
                
            </div>


<%content_for :right do%>
	<span class="span3">
		<%=render :partial=> "poll_filter"%>
	</span>
<%end%>

app/views/companies/user_review.html.erb
<link rel="stylesheet" href="/assets/jquery.mCustomScrollbar.css">

  
  <!-- custom scrollbar plugin -->
  <script src="/assets/jquery.mCustomScrollbar.concat.min.js"></script>
  
  <script>
    (function($){
      $(window).load(function(){
        
        $("a[rel='load-content']").click(function(e){
          e.preventDefault();
          var url=$(this).attr("href");
          $.get(url,function(data){
            $(".content .mCSB_container").append(data); //load new content inside .mCSB_container
            //scroll-to appended content 
            $(".content").mCustomScrollbar("scrollTo","h2:last");
          });
        });
        
        $(".content").delegate("a[href='top']","click",function(e){
          e.preventDefault();
          $(".content").mCustomScrollbar("scrollTo",$(this).attr("href"));
        });
        
      });
    })(jQuery);
  </script>

<%content_for :left do%>
	<span class="span3">
		 <%=render :partial=> "application/my_account_left"%>
	</span>
<%end%>


      <div class="reviews-box1">
              <div class="overflow12">
              <div class="review-center">
<div class="home-grid">
    <table cellpadding="0" cellspacing="0" class="grid-head-tbl">
        <tr>
            <td width="14%" align="center">Date</td>
            <td width="11%" align="center">Review</td>
            <td width="3%">&nbsp;</td>
            <td width="18%" align="left">Company</td>
            <td width="3%">&nbsp;</td>
            <td width="28%" align="center">Subject</td>
            <td width="19%" align="right">Comments</td>
            <td width="5%">&nbsp;</td>
        </tr>
    </table>
      <div class="content2 mCustomScrollbar">
                <table cellpadding="0" cellspacing="0" class="grid-tbl">
                  <%@reviews.each do |review| %>
                        <tr>
                            <td width="15%"><%=review.created_at.strftime("%d %b %Y")%></td>
                            <% if review.review_type == 'complaint'%>
                            <td width="9%" align="center" ><img src="/assets/red_star.png" alt=""></td>
                            <% else %>
                            <td width="9%" align="center"><img src="/assets/green_star.png" alt=""></td>
                            <% end %>
                            <td width="5%">&nbsp;</td>
                            <td width="21%" class="design"><%= link_to review.try(:company).try(:title),search_reviews_path(company_id: review.company_id) %></td>
                            <td width="2%">&nbsp;</td>
                            <td width="30%" class="design"><%= link_to review.title.truncate(20),review_path(review)  %></td>
                            <td width="19%">
                              <table class="comment-tbl">
                                <tr>
                                <%if review.comments.published.count > 0 and review.comments.published.last.user.present? and ['admin','agent'].include? review.comments.published.last.user.role %>
                                <td><img src="/assets/fill.png" alt=""><%=review.comments.published.count%><br><span>Company Response</span></td>
                                <% else %>
                                <td><img src="/assets/blank.png" alt=""> <%=review.comments.published.count%><br><br><span></span></td>
                                <% end %>
                                <td></td>
                                </tr>
                                </table>
                            </td>
    
                        </tr>
                                        
                      <% end %>
                        </table>
            </div>
      </div>
          </div>
      </div>
   </div>



<%content_for :right do%>
	<span class="span3">
		 <%=render :partial=> "review_filter"%>
	</span>
<%end%>