config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :nature_of_reviews
  end
  resources :search, :only => [:index]
  get "/search/reviews" => "reviews#search_reviews", as: :search_reviews
  # mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => {:registrations => "users/registrations",:sessions => "users/sessions", :confirmations => "users/confirmations"}
  root 'welcome#index'

  resources :admin, :only=>[:index]

  match 'searches' => 'admin#searches', via: [:get]
  resources :reviews do
	  resources :comments
  end
  match '/conversions'=> 'companies#conversions', as: :conversions, via: [:get, :post]
  match '/registered'=> 'companies#registered', as: :registered, via: [:get, :post]
  match '/unregistered'=> 'companies#unregistered', as: :unregistered, via: [:get, :post]
  match '/user-review'=> 'companies#user_review', as: :user_review, via: [:get, :post]
  match '/polls-bloopers'=> 'companies#polls_bloopers', as: :polls_bloopers, via: [:get, :post]

	get '/contact_us'=> 'contact_us#new', as: :contact_us

  resources :contact_us,:only => [:new, :create]
  resources :results
  resources :users,:only=>[:update,:edit]
  get '/resources/:slug' => 'resources#show', as: :resource


  match "/profile" => "users#show", via: [:get]
  match "/edit/profile" => "users#edit", via: [:get]
  match "/check_availiblity/user/preferred_alias"=> 'page#check_availiblity', via: [:get]
  get '/industry/companies_by_industry' => "reviews#companies_by_industry"
  get '/company/towns_by_company' => "reviews#towns_by_company"
  get '/town/locations_by_town_and_company' => "reviews#locations_by_town_and_company"
  get "/faqs" => "faqs#index",as: :faqs
  match "/:slug" => "pages#index",via: [:get],as: :page
  resources :polls ,:only => [:show]

  
  namespace :admin do
    resources :maintainences ,:only => [:index] do
      put "/toggle_status" => "maintainences#toggle_status"
    end

    put "/ticket_closed" => "reviews#ticket_closed"
    get "/searches/reviews" => "reviews#search_reviews", as: :search_reviews
    put '/assign_reviews'=> 'reviews#assign_reviews'
    get "change_password" => "users#change_password", as: :change_password
    put "update_password" => "users#update_password", as: :update_password

    get '/industry/companies_by_industry' => "reports#companies_by_industry"
    get '/company/towns_by_company' => "reports#towns_by_company"
    get '/town/locations_by_town_and_company' => "reports#locations_by_town_and_company"

    get '/total_reviews' => "reports#totalreviews"
    get '/nature_of_compliments' => "reports#nature_of_compliments"
    get '/nature_of_complaints2' => "reports#nature_of_complaints2"

    resources :monitor_jagents ,:only => [:index]
    resources :notifications ,:only => [:index]
    resources :customers ,:only => [:index]
  	resources :users
  	resources :locations
  	resources :towns
  	resources :companies
  	resources :industries
  	resources :nature_of_reviews
  	resources :reviews do
      resources :review_notes
      collection do 
        get :archive_reviews
        get :archive_files
      end
      put 'unpublished' => "reviews#unpublished"
  	  resources :comments do
        put 'unpublished_comment' => "comments#unpublished"
      end
  	end
  	#resources :addresses
    resources :contact_us, :only => [:index]
  	resources :polls
  	resources :faqs
  	resources :pages, :only => [:index, :edit, :update]
  	resources :resources
  	resources :agents
  	#resources :advertises
  	resources :suppliers
  	#resources :resource_types
    resources :seos
    #resources :company_performances
    #resources :abuse_reports
    
    
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_about_left.html.erb
  <div class="page-link">
          <ul>
              <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="<%= page_url(Page.first.slug) %>">About Us</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="<%= profile_path %>" class="selected"><%= @bc %></a></li>
            </ul>
        </div>
          <div class="section-one">
          <div class="reports">
              <div class="heading1">About Us</div>
               <% @pages.each do |page| %>
                <a href="<%= page_url(page.slug) %>"><div class="<%= (@sub_action == page.slug ? 'reports2 act' : 'reports2') %>"><%= page.title %></div></a>
                <% end %>
                
                <div class="clear"></div>
            </div>
            <div class="clear"></div>

               <%unless @performance.blank?%>
      <%unless @performance.performance_img.blank?%>
  
         <div class="polls newpolls">
       <%= link_to (image_tag @performance.performance_img,:style => "width:236px;height:230px;" ),@performance.worst_performance rescue nil%>
      </div>
      <%end%>
      <%#unless @performance.best_performance.blank?%>
      <!-- <div class="sectionLeftBot"> -->
       
       <%#= image_tag @performance.best_performance rescue nil%>
      <!-- </div> -->
    <%#end%>
    
  <%else%>

  <%end%>

            <div class="clear"></div>
         </div>
        
          
            
      
            
           
            
            
            
            
   

app/views/application/_ads_and_poll.html.erb
  <div class="section-third">
 <%unless @top_advertise.blank?%>
  <%if @top_advertise.image.present? %>
    <div class="polls newpolls" >
      <%#= @top_advertise.image rescue nil%>
      <%=link_to (image_tag @top_advertise.image.url ,:class=>"sectionRightAd",:style => "width:100%;height:230px;" ) , @top_advertise.link if @top_advertise%>
 
    </div>
  <%else%>
    <%#=link_to (image_tag @top_advertise.image.url ,:class=>"sectionRightAd",:style=>"width: 300px;") , @top_advertise.link if @top_advertise%>
  <%end%>
 <%end%>
 <%unless @bottom_advertise.blank?%>
  <%if @bottom_advertise.image.present?%>
    <div class="polls newpolls" >
        <%=link_to (image_tag @bottom_advertise.image.url ,:class=>"sectionRightAd", :style => "width:100%;height:230px;" ), @bottom_advertise.link  if @bottom_advertise%>
    </div>
  <%else%>
   <%#=link_to (image_tag @bottom_advertise.image.url ,:class=>"sectionRightAd", :style=>"width: 300px;"), @bottom_advertise.link  if @bottom_advertise%>
  <%end%>
 <%end%>


  <%if @poll.present?%>

    <div class="first-right-one">
    		   <%= form_for(@result) do |f| %>
		    <h3> <%= f.label @poll.title %></h3>
				
               
                
	        <% @poll.options.each do |option| %>
          <% if @poll.options.last.id == option.id %>
			       <div class="right-link-last">
              <%= f.radio_button :option_id, option.id, :class => "radio" %>
              <p style="margin-top:-1px">
              <%= option.answer %>
              </p>
				      <%= f.hidden_field :poll_id,value: option.poll_id%>
			      </div>
            <% else %>
             <div class="right-link">
              <%= f.radio_button :option_id, option.id,  :class => "radio"  %>
              <p style="margin-top:-1px">
              <%= option.answer %>
              </p>
              <%= f.hidden_field :poll_id,value: option.poll_id%>
            </div>
            <% end %>
			    <% end %>
				
				
		    <%= f.submit "Xema" ,:class=>"btn1" %>
		    
		   <% end %>
  </div>
  <!--  <div class="first-right-second"></div> -->
          <div class="clear"></div>
	<% end %>



</div>

app/views/application/_header.html.erb
 <script type="text/javascript">
 var RecaptchaOptions = {
    theme : 'white'
 };
 </script>
<div id="header-area">
  <% flash.each do |key, value| %>
     <div class="alert-box <%= key %>">
      <% if key == :alert %>
        <img src="/assets/wrong.png" style="float:left;margin:-7px 5px 0px -19px;">
      <% else %>
        <img src="/assets/right.png" style="float:left;margin:-7px 5px 0px -19px;">
      <% end %>
      <div> <%= value %></div></div>
  <% end %>
  

      <div id="logo"><a href="<%= root_path %>"><img src="/assets/xema-logo.png" alt="" title="Xema Xema"></a></div>
        <div id="right-head">
          <div class="join-us">Join us on</div>
            <div class="user-box">
            <% if user_signed_in? %>
              <div class="user">Hello <%= current_user.preferred_alias %></div>
              <div class="logout"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'signin-link'  %></div>
            <% else %>
               <div class="user2"> <%= link_to "Login", new_user_session_path %> / <%= link_to "Register", new_user_registration_path %></div>
            <% end %>
              <div class="social">
                  <ul>
                      <li style="margin-left:0px;"><a href="https://www.facebook.com/" target="_blank"><img src="/assets/icon-fb.png" alt="" title="Facebook"></a></li>
                        <li><a href="https://twitter.com/" target="_blank"><img src="/assets/icon-tw.png" alt="" title="Twitter" ></a></li>
                        <li><a href=" https://plus.google.com" target="_blank"><img src="/assets/icon-gp.png" alt="" title="Google Plus"></a></li>
                    </ul>
                </div>
            </div>
            <div class="search-box">
           <form action="/search" method="get">
              <input type="text" class="search-in" placeholder="SEARCH" name="search" id="searchh"><input type="submit" class="search-btn" value="">
          </form>
            </div>
        </div>
    </div>

app/views/application/_left.html.erb
<div class="sectionLeft">
  <ul class="sectionLeftTop">
    <li>
      <h3><a href="#" class="ribbon">View Reports</a></h3>
    </li>
    <li><%= link_to 'Review', reviews_path  ,:class=>(@sub_action == "review" ? "active":'') %></li>
    <li><%= link_to 'Polls', polls_bloopers_path  ,:class=>(@sub_action == "polls-bloopers" ? "active":'') %></li>
	  <li><%= link_to 'Registered Companies', registered_path  ,:class=>(@sub_action == "registered" ? "active":'') %></li>
	  <li><%= link_to 'Unregistered Companies', unregistered_path ,:class=>(@sub_action == "unregistered" ? "active":'')  %></li>
  </ul>
  <div class="sectionLeftBot"> Some stats e.g worst performing companies and best performing or quotes (flash or updated every week) </div>
</div>

app/views/application/_mid_tab.html.erb
<div class="tb">
	<ul>
		<li class="<%=(@active_tab == 'review') ? 'active' : ''%>"> <%= link_to 'Reviews', user_review_path  %></li>
		<li class="<%=(@active_tab == 'conversions') ? 'active' : ''%>"> <%= link_to 'Conversions', conversions_path  %></li>
	  <li class="<%=(@active_tab == 'registered') ? 'active' : ''%>">
	   <%= link_to 'Registered<br>Companies'.html_safe, registered_path  %></li>
	  <li class="<%=(@active_tab == 'unregistered') ? 'active' : ''%>"><%= link_to 'Companies not<br/>Registered'.html_safe, unregistered_path %></li>
		<li class="<%=(@active_tab == 'polls-bloopers') ? 'active' : ''%>"><%= link_to 'Polls&amp;Bloopers'.html_safe, polls_bloopers_path %></li>
	</ul>
</div>

app/views/application/_my_account_left.html.erb
  <%if params["controller"] == "users" %>
  <div class="page-link">
          <ul>
              <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="<%= profile_path %>">My Account</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="#" class="selected"><%= params["action"] == "edit" ? "Update Profile" : "My Profile"%></a></li>
            </ul>
        </div>

<% elsif  params["my"] == "mr" %>
  <div class="page-link">
          <ul>
                <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="<%= profile_path %>">My Account</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="<%= reviews_path %>" class="selected"> My Reviews</a></li>
            </ul>
</div>
<% elsif  params["search"]  %>
  <div class="page-link">
          <ul>
                <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="#" class="selected">Search Results</a></li>
            </ul>
</div>
<% elsif params["company_id"] %>
  <div class="page-link">
          <ul>
                <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <% unless params["action"] == "user_review" %>
                  <li><a href="<%= user_review_path %>">Reviews</a></li>
                  <li><span>&raquo;</span></li>
                <% end %>
                <li><a href="#" class="selected"><%= Company.find(params["company_id"]).title  %></a></li>
            </ul>
        </div>
<% elsif  @sub_action == "my_reviews" || @active_tab != "Home" %>
  <div class="page-link">
          <ul>
                <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <% unless params["action"] == "user_review" %>
                  <li><a href="<%= user_review_path %>">Reviews</a></li>
                  <li><span>&raquo;</span></li>
                <% end %>
                <li><a href="#" class="selected"><%= @active_tab.try(:titlecase)  %></a></li>
            </ul>
        </div>
<% end %>
  <div class="section-one">
          <div class="reports">
              
                <!--<ul>
                  <li class="current"><a href="#" class="current">Reviews</a></li>
                    <li><a href="#">Conversations</a></li>
                    <li><a href="#">Registered Companies</a></li>
                    <li><a href="#">Unregistered Companies</a></li>
                    <li><a href="#">Polls &amp; Bloppers</a></li>
                </ul>-->
                
                <%if user_signed_in? && params["controller"] == "users" || params["my"] %>
                <div class="heading1">My Account</div>
                 <a href="<%= profile_path %>">
                  <div class='<%=(@sub_action == "show_profile" ? "reports2 act" : "reports2")%>' >My Profile</div>
                </a>
               <a href="<%= edit_profile_path %>">
                <div class='<%=(@sub_action == "update_profile" ? "reports2 act" : "reports2")%>'>Update Profile</div>
              </a>
               <a href="<%= reviews_path %>?my=mr">
                <div class='<%=(@sub_action == "my_reviews" ? "reports2 act" : "reports2")%>'>My Reviews</div>
               </a>
               <a href="<%= root_path %>">
                <div class='<%=(@sub_action == "review" ? "reports2 act" : "reports2")%>'>Add a Review</div>
                </a>
                <% else %>
                <div class="heading1">View Reports</div>
                <a href="<%= user_review_path %>"><div class="<%=(@active_tab == "reviews" ? "reports2 act" : "reports2")%>">Reviews</div></a>
                <a href="<%= conversions_path %>"><div class="<%=(@active_tab == "conversions" ? "reports2 act" : "reports2")%>">Conversions</div></a>
                <a href="<%= registered_path %>"><div class="<%=(@active_tab == "registered_companies" ? "reports2 act" : "reports2")%>">Registered Companies</div></a>
                <a href="<%= unregistered_path %>"><div class="<%=(@active_tab == "unregistered_companies" ? "reports2 act" : "reports2")%>">Unregistered Companies</div></a>
                <a href="<%= polls_bloopers_path %>"><div class="<%=(@active_tab == "polls & bloopers" ? "reports2 act" : "reports2")%>">Polls &amp; Bloopers</div></a>
                <% end %>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
           
            <%unless @performance.blank?%>
             
      <%unless @performance.performance_img.blank?%>
	   <div class="polls newpolls">
			 <%= link_to (image_tag @performance.performance_img, :style => "width:100%;height:230px;"),@performance.worst_performance  rescue nil%>
	
      <%end%>
       </div>
    
      <%unless @performance.best_performance.blank?%>
         <div class="polls newpolls">
		  <!-- <div class="sectionLeftBot"> -->
		   <%= link_to (image_tag @performance.best_performance, :style => "width:100%;height:230px;"),@performance.worst_performance  rescue nil%>
		  <!-- </div> -->
           </div>
	  <%end%>
  
            
	<%else%>

  <%end%>
            
        </div>
 

app/views/application/_navigation.html.erb
    <div id="response-menu">
      <nav id="nav" role="navigation">
            <div id='cssmenu'>
                <ul>

          <li class='<%= @active_tab == "Home" ? "active" : "" %>'><a href='<%= root_path %>' class='<%= @active_tab == "Home" ? "active" : "" %>'><span>Home</span></a></li>
         
          <% active_tab = @sub_action == "my_reviews" ||  @nav_tab == "reviews"%>
          <li class='<%= active_tab ? "active" : "" %>' ><a href='<%= user_review_path %>' class='<%= active_tab ? "active" : "" %>' ><span>Reviews</span></a></li>
          
          <% if @resource_types%>
            <li class='<%= @action == "resources" ? "active" : "" %>'> <a href='<%= resource_path(@resource_types.last) %>' class='<%= @action == "resources" ? "active" : "" %>'><span>Resources</span></a></li>
          <% end %>

          <li class='<%= @action == "faqs" ? "active" : "" %>' ><a href='<%= faqs_url %>' class='<%= @action == "faqs" ? "active" : "" %>' ><span>FAQ</span></a></li>
          <% if user_signed_in? %>
           <li class='<%= @active_tab == "my_account" ? "active" : "" %>'> <a href='<%= profile_path %>' class='<%= @active_tab == "my_account" ? "active" : "" %>'><span>My Account</span></a></li>
          <% else %>
            <% active_tab = params["controller"] ==  "users/sessions" || params["controller"] ==  "users/registrations"%>
           <li class='<%= active_tab ? "active" : "" %>'><a href='<%= new_user_session_path %>' class='<%= active_tab ? "active" : "" %>'><span>My Account</span></a></li>
          <% end%>
          </li>
          <li class='<%= @action == "contact_us" ? "active" : "" %>'><a href='<%= contact_us_url %>'  class='<%= @action == "contact_us" ? "active last" : "last" %>'><span>Contact Us</span></a></li>
          </ul>
            </div>
            
        </nav>
    </div>

app/views/application/_resource_left.html.erb
  <div class="page-link">
          <ul>
                <li><a href="<%= root_path %>">Home</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="#">Resources</a></li>
                <li><span>&raquo;</span></li>
                <li><a href="#" class="selected"><%= @resource_type.name %></a></li>
                
            </ul>
        </div>  
 <div class="section-one">
         <div class="reports">
              <div class="heading1">Resources</div>
              <% @resource_types.reverse.each do |resource_type| %>
                <a href="<%= resource_path(resource_type.slug) %>">
                  <div class="<%= (@resource_type.slug == resource_type.slug ? "reports2 act" : 'reports2') if resource_type.resources.count > 0 %>">
                    <%= resource_type.name.titlecase if resource_type.resources.count > 0 %>
                  </div></a>
              <% end %>


                <div class="clear"></div>
            </div>
          <div class="clear"></div>
       
        

  <%unless @performance.blank?%>
      <%unless @performance.performance_img.blank?%>
           <div class="polls newpolls"> 
       <%= link_to (image_tag @performance.performance_img,:style => "width:236px;height:230px;" ),@performance.worst_performance  rescue nil%>
      </div>
      <%end%>
      <%#unless @performance.best_performance.blank?%>
        <!-- <div class="polls"> -->
          <%#=@performance.best_performance.html_safe rescue nil%>
      <!-- </div> -->
    <%#end%>
    
  <%else%>

  <%end%> 
</div>